name: Weekly Review Generation

on:
  schedule:
    # Run every Monday at 6 AM EST (11:00 UTC)
    - cron: '0 11 * * 1'
  workflow_dispatch: # Allow manual trigger

env:
  FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
  PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
  DATAFORSEO_LOGIN: ${{ secrets.DATAFORSEO_LOGIN }}
  DATAFORSEO_PASSWORD: ${{ secrets.DATAFORSEO_PASSWORD }}

jobs:
  generate-reviews:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Track new products
        run: node agents/product-tracker.js
        continue-on-error: true

      - name: Generate comprehensive reviews
        run: node agents/content-creator.js --type=review --count=1 --comprehensive
        continue-on-error: true

      - name: Generate product comparisons
        run: node agents/content-creator.js --type=comparison --count=2
        continue-on-error: true

      - name: Update buying guides
        run: node agents/content-creator.js --type=best --update-existing
        continue-on-error: true

      - name: Find and generate deal alerts
        run: node agents/deal-finder.js
        continue-on-error: true

      - name: Update content freshness
        run: node agents/content-updater.js
        continue-on-error: true

      - name: Validate content quality
        run: node agents/quality-check.js
        continue-on-error: true

      - name: Commit and push new content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/
          if git diff --staged --quiet; then
            echo "No content changes to commit"
          else
            git commit -m "📊 Weekly content update - $(date +%Y-%m-%d)

            Generated comprehensive content:
            - Product reviews with live data
            - Comparison guides
            - Updated buying guides
            - Deal alerts and price updates

            🤖 Generated with [Claude Code](https://claude.ai/code)
            
            Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
          fi

      - name: Trigger Vercel deployment
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
            echo "Triggered Vercel deployment"
          else
            echo "No Vercel deploy hook configured"
          fi